(* Generated by Garden *)
Require Import Garden.Garden.

(* Template signals *)
Module MainSignals.
  Record t : Set := {
    (* Input *)
    in_ : F.t;
    (* Output *)
    out : list F.t;
  }.
End MainSignals.

(* Template body *)
Definition Main : M.t (BlockUnit.t Empty_set) :=
  M.template_body [] (
    (* Signal Input *)
    do~ M.declare_signal "in" [[ ([] : list F.t) ]] in
    (* Signal Output *)
    do~ M.declare_signal "out" [[ [ 2 ] ]] in
    (* Component *)
    do~ M.declare_component "pedersen" in
    do~ M.substitute_var "pedersen" [[ M.call_function ~(| "Pedersen", [ 256 ] |) ]] in
    (* Component *)
    do~ M.declare_component "n2b" in
    do~ M.substitute_var "n2b" [[ M.call_function ~(| "Num2Bits", [ 253 ] |) ]] in
    (* Var *)
    do~ M.declare_var "i" [[ ([] : list F.t) ]] in
    do~ M.substitute_var "i" [[ 0 ]] in
    do~ M.substitute_var "n2b" [[ M.var (| "in" |) ]] in
    do~ M.substitute_var "i" [[ 0 ]] in
    do~ M.while [[ InfixOp.lesser ~(| M.var (| "i" |), 253 |) ]] (
      do~ M.substitute_var "pedersen" [[ M.var_access (| "n2b", [Access.Component "out"; Access.Array (M.var (| "i" |))] |) ]] in
      do~ M.substitute_var "i" [[ InfixOp.add ~(| M.var (| "i" |), 1 |) ]] in
      M.pure BlockUnit.Tt
    ) in
    do~ M.substitute_var "i" [[ 253 ]] in
    do~ M.while [[ InfixOp.lesser ~(| M.var (| "i" |), 256 |) ]] (
      do~ M.substitute_var "pedersen" [[ 0 ]] in
      do~ M.substitute_var "i" [[ InfixOp.add ~(| M.var (| "i" |), 1 |) ]] in
      M.pure BlockUnit.Tt
    ) in
    do~ M.substitute_var "out" [[ M.var_access (| "pedersen", [Access.Component "out"; Access.Array (0)] |) ]] in
    do~ M.substitute_var "out" [[ M.var_access (| "pedersen", [Access.Component "out"; Access.Array (1)] |) ]] in
    M.pure BlockUnit.Tt
  ).

(* Template not under-constrained *)
Definition Main_not_under_constrained in_ : Prop :=
  exists! out,
  let signals := MainSignals.Build_t in_ out in
  True (* NotUnderConstrained Main signals *).
