
(* Generated by Garden *)
Require Import Garden.Garden.

(* Template signals *)
Module EdDSAPoseidonVerifierSignals.
  Record t : Set := {
    enabled : F.t;
    Ax : F.t;
    Ay : F.t;
    S : F.t;
    R8x : F.t;
    R8y : F.t;
    M : F.t;
  }.
End EdDSAPoseidonVerifierSignals.

(* Template body *)
Definition EdDSAPoseidonVerifier : M.t (BlockUnit.t Empty_set) :=
  (* Signal Input *)
  do~ M.declare_signal "enabled" [[ ([] : list F.t) ]] in
  (* Signal Input *)
  do~ M.declare_signal "Ax" [[ ([] : list F.t) ]] in
  (* Signal Input *)
  do~ M.declare_signal "Ay" [[ ([] : list F.t) ]] in
  (* Signal Input *)
  do~ M.declare_signal "S" [[ ([] : list F.t) ]] in
  (* Signal Input *)
  do~ M.declare_signal "R8x" [[ ([] : list F.t) ]] in
  (* Signal Input *)
  do~ M.declare_signal "R8y" [[ ([] : list F.t) ]] in
  (* Signal Input *)
  do~ M.declare_signal "M" [[ ([] : list F.t) ]] in
  (* Var *)
  do~ M.declare_var "i" [[ ([] : list F.t) ]] in
  do~ M.substitute_var "i" [[ 0 ]] in
  (* Component *)
  do~ M.declare_component "snum2bits" in
  do~ M.substitute_var "snum2bits" [[ M.call_function ~(| "Num2Bits", [ 253 ] |) ]] in
  do~ M.substitute_var "snum2bits" [[ M.var ~(| "S" |) ]] in
  (* Component *)
  do~ M.declare_component "compConstant" in
  do~ M.substitute_var "compConstant" [[ M.call_function ~(| "CompConstant", [ 2736030358979909402780800718157159386076813972158567259200215660948447373040 ] |) ]] in
  do~ M.substitute_var "i" [[ 0 ]] in
  do~ M.while [[ InfixOp.lesser ~(| M.var ~(| "i" |), 253 |) ]] (
    do~ M.substitute_var "compConstant" [[ M.var_access ~(| "snum2bits", [Access.Component "out"; Access.Array (M.var ~(| "i" |))] |) ]] in
    do~ M.substitute_var "i" [[ InfixOp.add ~(| M.var ~(| "i" |), 1 |) ]] in
    M.pure BlockUnit.Tt
  ) in
  do~ M.substitute_var "compConstant" [[ 0 ]] in
  do~ M.equality_constraint
    [[ InfixOp.mul ~(| M.var_access ~(| "compConstant", [Access.Component "out"] |), M.var ~(| "enabled" |) |) ]]
    [[ 0 ]]
  in
  (* Component *)
  do~ M.declare_component "hash" in
  do~ M.substitute_var "hash" [[ M.call_function ~(| "Poseidon", [ 5 ] |) ]] in
  do~ M.substitute_var "hash" [[ M.var ~(| "R8x" |) ]] in
  do~ M.substitute_var "hash" [[ M.var ~(| "R8y" |) ]] in
  do~ M.substitute_var "hash" [[ M.var ~(| "Ax" |) ]] in
  do~ M.substitute_var "hash" [[ M.var ~(| "Ay" |) ]] in
  do~ M.substitute_var "hash" [[ M.var ~(| "M" |) ]] in
  (* Component *)
  do~ M.declare_component "h2bits" in
  do~ M.substitute_var "h2bits" [[ M.call_function ~(| "Num2Bits_strict", ([] : list F.t) |) ]] in
  do~ M.substitute_var "h2bits" [[ M.var_access ~(| "hash", [Access.Component "out"] |) ]] in
  (* Component *)
  do~ M.declare_component "dbl1" in
  do~ M.substitute_var "dbl1" [[ M.call_function ~(| "BabyDbl", ([] : list F.t) |) ]] in
  do~ M.substitute_var "dbl1" [[ M.var ~(| "Ax" |) ]] in
  do~ M.substitute_var "dbl1" [[ M.var ~(| "Ay" |) ]] in
  (* Component *)
  do~ M.declare_component "dbl2" in
  do~ M.substitute_var "dbl2" [[ M.call_function ~(| "BabyDbl", ([] : list F.t) |) ]] in
  do~ M.substitute_var "dbl2" [[ M.var_access ~(| "dbl1", [Access.Component "xout"] |) ]] in
  do~ M.substitute_var "dbl2" [[ M.var_access ~(| "dbl1", [Access.Component "yout"] |) ]] in
  (* Component *)
  do~ M.declare_component "dbl3" in
  do~ M.substitute_var "dbl3" [[ M.call_function ~(| "BabyDbl", ([] : list F.t) |) ]] in
  do~ M.substitute_var "dbl3" [[ M.var_access ~(| "dbl2", [Access.Component "xout"] |) ]] in
  do~ M.substitute_var "dbl3" [[ M.var_access ~(| "dbl2", [Access.Component "yout"] |) ]] in
  (* Component *)
  do~ M.declare_component "isZero" in
  do~ M.substitute_var "isZero" [[ M.call_function ~(| "IsZero", ([] : list F.t) |) ]] in
  do~ M.substitute_var "isZero" [[ M.var_access ~(| "dbl3", [Access.Component "x"] |) ]] in
  do~ M.equality_constraint
    [[ InfixOp.mul ~(| M.var_access ~(| "isZero", [Access.Component "out"] |), M.var ~(| "enabled" |) |) ]]
    [[ 0 ]]
  in
  (* Component *)
  do~ M.declare_component "mulAny" in
  do~ M.substitute_var "mulAny" [[ M.call_function ~(| "EscalarMulAny", [ 254 ] |) ]] in
  do~ M.substitute_var "i" [[ 0 ]] in
  do~ M.while [[ InfixOp.lesser ~(| M.var ~(| "i" |), 254 |) ]] (
    do~ M.substitute_var "mulAny" [[ M.var_access ~(| "h2bits", [Access.Component "out"; Access.Array (M.var ~(| "i" |))] |) ]] in
    do~ M.substitute_var "i" [[ InfixOp.add ~(| M.var ~(| "i" |), 1 |) ]] in
    M.pure BlockUnit.Tt
  ) in
  do~ M.substitute_var "mulAny" [[ M.var_access ~(| "dbl3", [Access.Component "xout"] |) ]] in
  do~ M.substitute_var "mulAny" [[ M.var_access ~(| "dbl3", [Access.Component "yout"] |) ]] in
  (* Component *)
  do~ M.declare_component "addRight" in
  do~ M.substitute_var "addRight" [[ M.call_function ~(| "BabyAdd", ([] : list F.t) |) ]] in
  do~ M.substitute_var "addRight" [[ M.var ~(| "R8x" |) ]] in
  do~ M.substitute_var "addRight" [[ M.var ~(| "R8y" |) ]] in
  do~ M.substitute_var "addRight" [[ M.var_access ~(| "mulAny", [Access.Component "out"; Access.Array (0)] |) ]] in
  do~ M.substitute_var "addRight" [[ M.var_access ~(| "mulAny", [Access.Component "out"; Access.Array (1)] |) ]] in
  (* Var *)
  do~ M.declare_var "BASE8" [[ [ 2 ] ]] in
  do~ M.substitute_var "BASE8" [[ array_with_repeat (0) (2) ]] in
  do~ M.substitute_var "BASE8" [[ [ 5299619240641551281634865583518297030282874472190772894086521144482721001553; 16950150798460657717958625567821834550301663161624707787222815936182638968203 ] ]] in
  (* Component *)
  do~ M.declare_component "mulFix" in
  do~ M.substitute_var "mulFix" [[ M.call_function ~(| "EscalarMulFix", [ 253; M.var ~(| "BASE8" |) ] |) ]] in
  do~ M.substitute_var "i" [[ 0 ]] in
  do~ M.while [[ InfixOp.lesser ~(| M.var ~(| "i" |), 253 |) ]] (
    do~ M.substitute_var "mulFix" [[ M.var_access ~(| "snum2bits", [Access.Component "out"; Access.Array (M.var ~(| "i" |))] |) ]] in
    do~ M.substitute_var "i" [[ InfixOp.add ~(| M.var ~(| "i" |), 1 |) ]] in
    M.pure BlockUnit.Tt
  ) in
  (* Component *)
  do~ M.declare_component "eqCheckX" in
  do~ M.substitute_var "eqCheckX" [[ M.call_function ~(| "ForceEqualIfEnabled", ([] : list F.t) |) ]] in
  do~ M.substitute_var "eqCheckX" [[ M.var ~(| "enabled" |) ]] in
  do~ M.substitute_var "eqCheckX" [[ M.var_access ~(| "mulFix", [Access.Component "out"; Access.Array (0)] |) ]] in
  do~ M.substitute_var "eqCheckX" [[ M.var_access ~(| "addRight", [Access.Component "xout"] |) ]] in
  (* Component *)
  do~ M.declare_component "eqCheckY" in
  do~ M.substitute_var "eqCheckY" [[ M.call_function ~(| "ForceEqualIfEnabled", ([] : list F.t) |) ]] in
  do~ M.substitute_var "eqCheckY" [[ M.var ~(| "enabled" |) ]] in
  do~ M.substitute_var "eqCheckY" [[ M.var_access ~(| "mulFix", [Access.Component "out"; Access.Array (1)] |) ]] in
  do~ M.substitute_var "eqCheckY" [[ M.var_access ~(| "addRight", [Access.Component "yout"] |) ]] in
  M.pure BlockUnit.Tt.
