opam-version: "2.0"
name: "rocq-garden"
version: "0.1.0"
synopsis: "Garden"
description: """
Formal verification for zero-knowledge circuits
"""
maintainer: "Guillaume Claret <dev@clarus.me>"
authors: [
  "Formal Land <contact@formal.land>"
]
license: "MIT"
homepage: "https://github.com/formal-land/garden"
bug-reports: "https://github.com/formal-land/garden/issues"
dev-repo: "git+https://github.com/formal-land/garden.git"
depends: [
  "rocq-core" {= "9.0.1"}
  "rocq-stdlib" {= "9.0.0"}
  "coq-coqutil" {>= "0.0.7"}
  "coq-hammer" {= "1.3.2+9.0"}
  "rocq-mathcomp-algebra" {>= "2.4.0" & < "2.6~"}
  "rocq-smpl" {= "9.0"}
]
build: [
  [make]
]
