#!/usr/bin/env python3
"""Generate the pinned verifying-key byte/literal files for the
transcript_repr byte channel:

  Garden/Orchard/vk_pinned_bytes.v  -- the pretty Debug dump
      orchard/src/circuit_data/circuit_description_fixed imported as
      sharded PrimString literals (untrusted witness input, certified
      byte-for-byte by the T1 parity certificate);
  Garden/Orchard/vk_pinned_data.v   -- the pinned literals the printer
      needs that the model does not derive: the two modulus strings, the
      extended_k domain constant, minimum_degree, and the 44 commitment
      coordinate pairs (29 fixed + 15 permutation Vesta points).

Usage (from the repository root, with ../orchard checked out beside it):

  python3 scripts/generate_vk_pinned.py

The dump path can be overridden with a single argument.
"""
import re
import sys
import os

DUMP = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
    os.path.dirname(__file__),
    "..", "..", "orchard", "src", "circuit_data", "circuit_description_fixed")
ROOT = os.path.join(os.path.dirname(__file__), "..")
SHARD_SIZE = 65536

with open(DUMP, "rb") as f:
    raw = f.read()
assert raw.endswith(b"}\n"), "unexpected dump tail"
assert all(b < 128 for b in raw), "dump is not ASCII"
text = raw.decode("ascii")

CMD = "python3 scripts/generate_vk_pinned.py"


def pstring_literal(chunk: str) -> str:
    return '"' + chunk.replace('"', '""') + '"'


# ---- vk_pinned_bytes.v ----
shards = [text[i:i + SHARD_SIZE] for i in range(0, len(text), SHARD_SIZE)]
lines = []
lines.append("(** * The pinned verifying-key Debug dump, as primitive-string shards.")
lines.append("")
lines.append("    The byte-for-byte content of")
lines.append("    [orchard/src/circuit_data/circuit_description_fixed] (the pretty")
lines.append("    [format!(\"{:#?}\\n\", vk.pinned())] Debug dump of the deployed")
lines.append(f"    verifying key; {len(raw)} bytes), imported as {len(shards)}")
lines.append(f"    PrimString literals of at most {SHARD_SIZE} bytes.  Untrusted")
lines.append("    witness input: the T1 parity certificate ([vk_pinned_parity.v])")
lines.append("    proves the in-model printer reproduces exactly these bytes.")
lines.append("")
lines.append(f"    Generated by [scripts/generate_vk_pinned.py]; regenerate with:")
lines.append(f"      {CMD} *)")
lines.append("")
lines.append("Require Import Stdlib.Strings.PrimString.")
lines.append("")
lines.append("Local Open Scope pstring_scope.")
lines.append("")
lines.append("Module VkPinnedBytes.")
lines.append("")
for i, shard in enumerate(shards):
    lines.append(f"Definition shard_{i:02d} : PrimString.string :=")
    lines.append(f"  {pstring_literal(shard)}.")
    lines.append("")
lines.append("(** The whole dump, all shards concatenated in order. *)")
lines.append("Definition dump : PrimString.string :=")
parts = " (PrimString.cat ".join(f"shard_{i:02d}" for i in range(len(shards)))
lines.append("  PrimString.cat ".join([""]) or None)
lines.pop()
expr = f"shard_{len(shards)-1:02d}"
for i in range(len(shards) - 2, -1, -1):
    expr = f"PrimString.cat shard_{i:02d} ({expr})"
lines.append(f"  {expr}.")
lines.append("")
lines.append("End VkPinnedBytes.")
lines.append("")
with open(os.path.join(ROOT, "Garden", "Orchard", "vk_pinned_bytes.v"), "w") as f:
    f.write("\n".join(lines))
print(f"vk_pinned_bytes.v: {len(shards)} shards, {len(raw)} bytes")

# ---- extract literals for vk_pinned_data.v ----
m = re.search(r'^    base_modulus: "(0x[0-9a-f]+)",$', text, re.M)
base_modulus = m.group(1)
m = re.search(r'^    scalar_modulus: "(0x[0-9a-f]+)",$', text, re.M)
scalar_modulus = m.group(1)
m = re.search(r'^        extended_k: (\d+),$', text, re.M)
extended_k = int(m.group(1))
m = re.search(r'^        minimum_degree: None,$', text, re.M)
assert m, "minimum_degree is not None"

point_re = re.compile(r'^ {8}\((0x[0-9a-f]{64}), (0x[0-9a-f]{64})\),$', re.M)
fixed_block = text.split("    fixed_commitments: [\n")[1].split("    ],\n")[0]
fixed_comm = point_re.findall(fixed_block)
perm_re = re.compile(r'^ {12}\((0x[0-9a-f]{64}), (0x[0-9a-f]{64})\),$', re.M)
perm_block = text.split("        commitments: [\n")[1].split("        ],\n")[0]
perm_comm = perm_re.findall(perm_block)
assert len(fixed_comm) == 29 and len(perm_comm) == 15, (len(fixed_comm), len(perm_comm))

lines = []
lines.append("(** * Pinned verifying-key literals for the transcript byte channel.")
lines.append("")
lines.append("    The components of the pinned verifying-key description")
lines.append("    ([orchard/src/circuit_data/circuit_description_fixed]) that the")
lines.append("    model does not derive: the base/scalar modulus strings, the")
lines.append("    [extended_k] domain constant, [minimum_degree], and the 44")
lines.append("    commitment coordinate pairs (29 fixed-column + 15 permutation")
lines.append("    commitments, affine Vesta points; the model computes no MSM, so")
lines.append("    the coordinates are witness input exactly like the fingerprint")
lines.append("    literals of [circuit_compiled_pinned.v]).  Untrusted witness")
lines.append("    input, certified byte-for-byte against the dump by the T1 parity")
lines.append("    certificate ([vk_pinned_parity.v]).")
lines.append("")
lines.append(f"    Generated by [scripts/generate_vk_pinned.py]; regenerate with:")
lines.append(f"      {CMD} *)")
lines.append("")
lines.append("Require Import Stdlib.Lists.List.")
lines.append("Require Import Stdlib.ZArith.ZArith.")
lines.append("Require Import Stdlib.Strings.PrimString.")
lines.append("")
lines.append("Import ListNotations.")
lines.append("Local Open Scope Z_scope.")
lines.append("")
lines.append("Module VkPinnedData.")
lines.append("")
lines.append("(** [C::Base::MODULUS] and [C::Scalar::MODULUS] for [C = vesta::Affine],")
lines.append("    as printed (the quotes are added by the string Debug rendering). *)")
lines.append("Definition base_modulus : PrimString.string :=")
lines.append(f'  "{base_modulus}"%pstring.')
lines.append("")
lines.append("Definition scalar_modulus : PrimString.string :=")
lines.append(f'  "{scalar_modulus}"%pstring.')
lines.append("")
lines.append("(** The extended evaluation-domain size exponent ([k = 11] is pinned in")
lines.append("    [PolyDomain.k]). *)")
lines.append(f"Definition extended_k : Z := {extended_k}.")
lines.append("")
lines.append("Definition minimum_degree : option Z := None.")
lines.append("")
lines.append("(** The 29 fixed-column commitments, affine (x, y) coordinates. *)")
lines.append("Definition fixed_commitments : list (Z * Z) := [")
for i, (x, y) in enumerate(fixed_comm):
    sep = ";" if i + 1 < len(fixed_comm) else ""
    lines.append(f"  ({x},")
    lines.append(f"   {y}){sep}")
lines.append("].")
lines.append("")
lines.append("(** The 15 permutation commitments, affine (x, y) coordinates. *)")
lines.append("Definition permutation_commitments : list (Z * Z) := [")
for i, (x, y) in enumerate(perm_comm):
    sep = ";" if i + 1 < len(perm_comm) else ""
    lines.append(f"  ({x},")
    lines.append(f"   {y}){sep}")
lines.append("].")
lines.append("")
lines.append("End VkPinnedData.")
lines.append("")
with open(os.path.join(ROOT, "Garden", "Orchard", "vk_pinned_data.v"), "w") as f:
    f.write("\n".join(lines))
print("vk_pinned_data.v: moduli + extended_k + 44 commitment pairs")
