#!/usr/bin/env python3
"""Generate the Rocq replay table for Halo2 constant fixed-column cells.

The Orchard synthesis model is written at the level of the Rust synthesis
structure. Halo2's floor planner additionally assigns fixed-column constants
after the logical regions have been synthesized. These events are mechanical,
so we keep them in a generated Rocq table derived from the Rust implementation
JSON.
"""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
IMPLEMENTATION_JSON = (
    ROOT
    / "Garden"
    / "Orchard"
    / "Snapshots"
    / "circuit_synthesis_generated_from_implementation.json"
)
OUTPUT = ROOT / "Garden" / "Orchard" / "circuit_synthesis_constants.v"


def coq_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def fixed_cell_index(cell: dict) -> tuple[str, str]:
    column = cell["column"]
    return column["kind"], column["index"]


def extract_constant_suffix(events: list[dict]) -> list[tuple[dict, dict]]:
    pairs: list[tuple[dict, dict]] = []
    index = len(events)

    while index >= 2:
        assign = events[index - 2]
        copy = events[index - 1]
        if assign.get("tag") != "AssignFixed" or copy.get("tag") != "Copy":
            break

        left = copy["left"]
        right = copy["right"]
        left_kind, left_index = fixed_cell_index(left)
        right_kind, _ = fixed_cell_index(right)

        if (
            assign["column"] != "3"
            or left_kind != "Fixed"
            or left_index != assign["column"]
            or left["row"] != assign["row"]
            or right_kind != "Advice"
        ):
            break

        pairs.append((assign, copy))
        index -= 2

    pairs.reverse()
    if not pairs:
        raise SystemExit("no trailing constant fixed-column events found")

    return pairs


def render(pairs: list[tuple[dict, dict]]) -> str:
    lines: list[str] = [
        "(* Generated by scripts/generate_orchard_synthesis_constants.py.",
        "   Contains only Halo2 floor-planner constant fixed-column bindings. *)",
        "",
        "Require Import Garden.Halo2.Synthesis.",
        "",
        "Require Export Stdlib.Lists.List.",
        "Require Export Stdlib.Strings.PrimString.",
        "Require Export Stdlib.ZArith.ZArith.",
        "",
        "Import ListNotations.",
        "Export PStringNotations.",
        "Global Open Scope pstring_scope.",
        "Global Open Scope Z_scope.",
        "",
        "Module ConstantCopy.",
        "  Record t : Set := {",
        "    fixed_row : Z;",
        "    annotation : string;",
        "    value : Z;",
        "    advice_column : Z;",
        "    advice_row : Z;",
        "  }.",
        "End ConstantCopy.",
        "",
        "Definition fixed_cell (row : Z) : Raw.Cell.t := {|",
        "  Raw.Cell.column := {|",
        "    Raw.ColumnRef.kind := Raw.ColumnKind.Fixed;",
        "    Raw.ColumnRef.index := 3;",
        "  |};",
        "  Raw.Cell.row := row;",
        "|}.",
        "",
        "Definition advice_cell (column row : Z) : Raw.Cell.t := {|",
        "  Raw.Cell.column := {|",
        "    Raw.ColumnRef.kind := Raw.ColumnKind.Advice;",
        "    Raw.ColumnRef.index := column;",
        "  |};",
        "  Raw.Cell.row := row;",
        "|}.",
        "",
        "Definition to_events (entry : ConstantCopy.t) : list Raw.Event.t :=",
        "  [",
        "    Raw.Event.AssignFixed",
        "      3",
        "      entry.(ConstantCopy.fixed_row)",
        "      entry.(ConstantCopy.annotation)",
        "      entry.(ConstantCopy.value);",
        "    Raw.Event.Copy",
        "      (fixed_cell entry.(ConstantCopy.fixed_row))",
        "      (advice_cell",
        "        entry.(ConstantCopy.advice_column)",
        "        entry.(ConstantCopy.advice_row))",
        "  ].",
        "",
        "Fixpoint to_event_list (entries : list ConstantCopy.t) : list Raw.Event.t :=",
        "  match entries with",
        "  | [] => []",
        "  | entry :: entries => to_events entry ++ to_event_list entries",
        "  end.",
        "",
        "Definition constant_copies : list ConstantCopy.t :=",
        "  [",
    ]

    for index, (assign, copy) in enumerate(pairs):
        right = copy["right"]
        advice_column = right["column"]["index"]
        advice_row = right["row"]
        separator = ";" if index + 1 < len(pairs) else ""
        lines.extend(
            [
                "    {|",
                f"      ConstantCopy.fixed_row := {assign['row']};",
                f"      ConstantCopy.annotation := {coq_string(assign['annotation'])};",
                f"      ConstantCopy.value := {assign['value']};",
                f"      ConstantCopy.advice_column := {advice_column};",
                f"      ConstantCopy.advice_row := {advice_row};",
                f"    |}}{separator}",
            ]
        )

    lines.extend(
        [
            "  ].",
            "",
            "Definition events : list Raw.Event.t :=",
            "  to_event_list constant_copies.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    data = json.loads(IMPLEMENTATION_JSON.read_text())
    pairs = extract_constant_suffix(data["events"])
    OUTPUT.write_text(render(pairs))
    print(f"wrote {OUTPUT} with {len(pairs)} constant fixed-column bindings")


if __name__ == "__main__":
    main()
