(* Generated by orchard::circuit::generate_action_circuit_synthesis_json.
   Contains only V1 floor-planner region starts. *)

Require Export Stdlib.Lists.List.
Require Export Stdlib.ZArith.ZArith.
Require Import Garden.Orchard.regions.

Import ListNotations.
Global Open Scope Z_scope.

Definition region_starts : list Z :=
  [
    1768;
    1770;
    1762;
    1763;
    1764;
    1769;
    1773;
    1772;
    1758;
    333;
    751;
    742;
    332;
    331;
    1288;
    1737;
    1761;
    330;
    700;
    682;
    329;
    328;
    1341;
    1727;
    1755;
    334;
    1773;
    652;
    325;
    297;
    917;
    1713;
    1750;
    321;
    721;
    1664;
    318;
    317;
    1500;
    1719;
    1753;
    313;
    1770;
    1767;
    310;
    309;
    1076;
    1731;
    1757;
    305;
    1706;
    1697;
    303;
    302;
    1553;
    1743;
    1747;
    301;
    1658;
    1606;
    300;
    299;
    864;
    1741;
    1752;
    298;
    670;
    649;
    296;
    295;
    970;
    1733;
    1759;
    294;
    607;
    604;
    293;
    292;
    1129;
    1721;
    1760;
    291;
    613;
    622;
    290;
    289;
    1394;
    1725;
    1756;
    288;
    658;
    661;
    287;
    286;
    1235;
    1729;
    1754;
    285;
    1776;
    694;
    284;
    283;
    1447;
    1735;
    1751;
    282;
    730;
    733;
    281;
    280;
    1182;
    1739;
    1749;
    279;
    1615;
    1627;
    278;
    277;
    811;
    1717;
    1746;
    276;
    1667;
    1676;
    275;
    274;
    1023;
    1723;
    1748;
    312;
    1709;
    1755;
    327;
    314;
    758;
    1715;
    1744;
    319;
    1761;
    1758;
    318;
    317;
    1235;
    1731;
    1746;
    316;
    1694;
    1691;
    274;
    275;
    1023;
    1723;
    1657;
    276;
    1673;
    1670;
    277;
    278;
    970;
    1713;
    1739;
    279;
    1636;
    1633;
    280;
    281;
    1129;
    1715;
    1740;
    282;
    1612;
    1609;
    283;
    284;
    1394;
    1737;
    1742;
    285;
    739;
    736;
    286;
    287;
    1500;
    1735;
    1743;
    288;
    715;
    712;
    289;
    290;
    1553;
    1733;
    1750;
    291;
    691;
    688;
    292;
    293;
    1341;
    1729;
    1747;
    294;
    667;
    664;
    295;
    296;
    758;
    1727;
    1748;
    297;
    643;
    640;
    298;
    299;
    1288;
    1725;
    1751;
    300;
    619;
    616;
    301;
    302;
    1447;
    1721;
    1752;
    303;
    601;
    598;
    304;
    305;
    1182;
    1717;
    1753;
    306;
    610;
    625;
    307;
    308;
    1076;
    1651;
    1749;
    320;
    637;
    646;
    329;
    309;
    917;
    1643;
    1754;
    310;
    697;
    706;
    311;
    312;
    864;
    1647;
    1741;
    313;
    1618;
    1639;
    314;
    315;
    811;
    1655;
    757;
    1642;
    1658;
    1691;
    418;
    1699;
    1697;
    272;
    250;
    1606;
    273;
    247;
    1693;
    524;
    253;
    1701;
    673;
    1703;
    1711;
    304;
    1700;
    1703;
    306;
    307;
    1764;
    308;
    333;
    1689;
    1606;
    1685;
    538;
    381;
    1709;
    0;
    311;
    566;
    247;
    1767;
    0;
    315;
    655;
    1688;
    316;
    319;
    1685;
    320;
    1661;
    745;
    322;
    323;
    718;
    324;
    685;
    326;
    673;
    634;
    247;
    496;
    1645;
    631;
    628;
    325;
    426;
    1653;
    503;
    1687;
    137;
    1707;
    468;
    366;
    351;
    552;
    256;
    260;
    268;
    266;
    269;
    586;
    580;
    596;
    594;
    582;
    0;
    1766;
    1765;
    1771;
    321;
    676;
    679;
    322;
    323;
    703;
    324;
    709;
    724;
    325;
    326;
    727;
    327;
    748;
    328;
    754;
    1621;
    273;
    510;
    1719;
    1624;
    1630;
    299;
    454;
    1649;
    588;
    1695;
    137;
    1705;
    482;
    411;
    396;
    440;
    258;
    262;
    270;
    264;
    271;
    592;
    590;
    597;
    588;
    584;
    1745;
    1681
  ].

Fixpoint region_start_of_list (index : Z) (starts : list Z) : Z :=
  match starts with
  | [] => 0
  | start :: starts =>
      if Z.eqb index 0 then start else region_start_of_list (index - 1) starts
  end.

Definition witness_input_index (region : RegionId.WitnessInput.t) : Z :=
  match region with
  | RegionId.WitnessInput.PsiOld => 0
  | RegionId.WitnessInput.RhoOld => 1
  | RegionId.WitnessInput.CmOld => 2
  | RegionId.WitnessInput.GDOld => 3
  | RegionId.WitnessInput.AkP => 4
  | RegionId.WitnessInput.Nk => 5
  | RegionId.WitnessInput.VOld => 6
  | RegionId.WitnessInput.VNew => 7
  end.

Definition merkle_region_offset (region : RegionId.Merkle.Region.t) : Z :=
  match region with
  | RegionId.Merkle.Region.NodePosition => 0
  | RegionId.Merkle.Region.WitnessA => 1
  | RegionId.Merkle.Region.RangeB1 => 2
  | RegionId.Merkle.Region.RangeB2 => 3
  | RegionId.Merkle.Region.WitnessB => 4
  | RegionId.Merkle.Region.WitnessC => 5
  | RegionId.Merkle.Region.HashToPoint => 6
  | RegionId.Merkle.Region.Decomposition => 7
  end.

Definition merkle_index
    (layer : RegionId.Merkle.Layer.t)
    (region : RegionId.Merkle.Region.t) : Z :=
  8 + 8 * RegionId.Merkle.Layer.to_index layer + merkle_region_offset region.

Definition poseidon_index (region : RegionId.Poseidon.t) : Z :=
  match region with
  | RegionId.Poseidon.InitialState => 271
  | RegionId.Poseidon.AddInput => 272
  | RegionId.Poseidon.PermuteState => 273
  | RegionId.Poseidon.FullRound => 0
  | RegionId.Poseidon.PartialRounds => 0
  | RegionId.Poseidon.PadAndAdd => 0
  end.

Definition value_commitment_index (region : RegionId.ValueCommitment.t) : Z :=
  match region with
  | RegionId.ValueCommitment.MagnitudeRangeCheck => 264
  | RegionId.ValueCommitment.SignRangeCheck => 265
  | RegionId.ValueCommitment.ValueCommitVIncomplete => 266
  | RegionId.ValueCommitment.ValueCommitVMsb => 267
  | RegionId.ValueCommitment.ValueCommitRIncomplete => 268
  | RegionId.ValueCommitment.ValueCommitRLast => 269
  | RegionId.ValueCommitment.CompletePointAdd => 270
  end.

Definition nullifier_index (region : RegionId.Nullifier.t) : Z :=
  match region with
  | RegionId.Nullifier.ScalarAdd => 274
  | RegionId.Nullifier.BaseFieldIncomplete => 275
  | RegionId.Nullifier.BaseFieldComplete => 276
  | RegionId.Nullifier.AlphaLookup => 277
  | RegionId.Nullifier.CanonicityChecks => 278
  | RegionId.Nullifier.CompletePointAdd => 279
  end.

Definition spend_authority_index (region : RegionId.SpendAuthority.t) : Z :=
  match region with
  | RegionId.SpendAuthority.FullFixedIncomplete => 280
  | RegionId.SpendAuthority.FullFixedLast => 281
  | RegionId.SpendAuthority.CompletePointAdd => 282
  end.

Definition address_integrity_mul_index
    (region : RegionId.AddressIntegrity.Mul.t) : Z :=
  match region with
  | RegionId.AddressIntegrity.Mul.VariableBase => 297
  | RegionId.AddressIntegrity.Mul.OverflowS => 298
  | RegionId.AddressIntegrity.Mul.OverflowLookup => 299
  | RegionId.AddressIntegrity.Mul.OverflowCheck => 300
  end.

Definition address_integrity_index
    (region : RegionId.AddressIntegrity.t) : Z :=
  match region with
  | RegionId.AddressIntegrity.Mul region =>
      address_integrity_mul_index region
  | RegionId.AddressIntegrity.WitnessPkD => 301
  | RegionId.AddressIntegrity.Equality => 302
  end.

Definition commit_ivk_index (region : RegionId.CommitIvk.t) : Z :=
  match region with
  | RegionId.CommitIvk.WitnessA => 283
  | RegionId.CommitIvk.RangeB0 => 284
  | RegionId.CommitIvk.RangeB2 => 285
  | RegionId.CommitIvk.WitnessB => 286
  | RegionId.CommitIvk.WitnessC => 287
  | RegionId.CommitIvk.RangeD0 => 288
  | RegionId.CommitIvk.WitnessD => 289
  | RegionId.CommitIvk.FixedBaseIncomplete => 290
  | RegionId.CommitIvk.FixedBaseLast => 291
  | RegionId.CommitIvk.HashToPoint => 292
  | RegionId.CommitIvk.CompletePointAdd => 293
  | RegionId.CommitIvk.AkLookup => 294
  | RegionId.CommitIvk.NkLookup => 295
  | RegionId.CommitIvk.CanonicityGate => 296
  end.

Definition note_commit_base (which : RegionId.NoteCommit.Which.t) : Z :=
  match which with
  | RegionId.NoteCommit.Which.Old => 303
  | RegionId.NoteCommit.Which.New => 350
  end.

Definition note_commit_y_subject_base
    (subject : RegionId.NoteCommit.YSubject.t) : Z :=
  match subject with
  | RegionId.NoteCommit.YSubject.GD => 15
  | RegionId.NoteCommit.YSubject.PkD => 20
  end.

Definition note_commit_y_canonicity_offset
    (region : RegionId.NoteCommit.YCanonicity.t) : Z :=
  match region with
  | RegionId.NoteCommit.YCanonicity.RangeK0 => 0
  | RegionId.NoteCommit.YCanonicity.RangeK2 => 1
  | RegionId.NoteCommit.YCanonicity.JLookup => 2
  | RegionId.NoteCommit.YCanonicity.JPrimeLookup => 3
  | RegionId.NoteCommit.YCanonicity.Gate => 4
  end.

Definition note_commit_offset (region : RegionId.NoteCommit.t) : Z :=
  match region with
  | RegionId.NoteCommit.WitnessA => 0
  | RegionId.NoteCommit.RangeB0 => 1
  | RegionId.NoteCommit.RangeB3 => 2
  | RegionId.NoteCommit.WitnessB => 3
  | RegionId.NoteCommit.WitnessC => 4
  | RegionId.NoteCommit.RangeD2 => 5
  | RegionId.NoteCommit.WitnessD => 6
  | RegionId.NoteCommit.RangeE0 => 7
  | RegionId.NoteCommit.RangeE1 => 8
  | RegionId.NoteCommit.WitnessE => 9
  | RegionId.NoteCommit.WitnessF => 10
  | RegionId.NoteCommit.RangeG1 => 11
  | RegionId.NoteCommit.WitnessG => 12
  | RegionId.NoteCommit.RangeH0 => 13
  | RegionId.NoteCommit.WitnessH => 14
  | RegionId.NoteCommit.YCanonicity subject region =>
      note_commit_y_subject_base subject
        + note_commit_y_canonicity_offset region
  | RegionId.NoteCommit.FixedBaseIncomplete => 25
  | RegionId.NoteCommit.FixedBaseLast => 26
  | RegionId.NoteCommit.HashToPoint => 27
  | RegionId.NoteCommit.CompletePointAdd => 28
  | RegionId.NoteCommit.XGDLookup => 29
  | RegionId.NoteCommit.XPKDLookup => 30
  | RegionId.NoteCommit.RhoLookup => 31
  | RegionId.NoteCommit.PsiLookup => 32
  | RegionId.NoteCommit.MessagePieceB => 33
  | RegionId.NoteCommit.MessagePieceD => 34
  | RegionId.NoteCommit.MessagePieceE => 35
  | RegionId.NoteCommit.MessagePieceG => 36
  | RegionId.NoteCommit.MessagePieceH => 37
  | RegionId.NoteCommit.InputGD => 38
  | RegionId.NoteCommit.InputPkD => 39
  | RegionId.NoteCommit.InputValue => 40
  | RegionId.NoteCommit.InputRho => 41
  | RegionId.NoteCommit.InputPsi => 42
  end.

Definition note_commit_index
    (which : RegionId.NoteCommit.Which.t)
    (region : RegionId.NoteCommit.t) : Z :=
  note_commit_base which + note_commit_offset region.

Definition gadget_local_index (_ : RegionId.GadgetLocal.t) : Z :=
  0.

Definition region_index_of (region : RegionId.t) : Z :=
  match region with
  | RegionId.WitnessInput region => witness_input_index region
  | RegionId.Merkle layer region => merkle_index layer region
  | RegionId.Poseidon region => poseidon_index region
  | RegionId.ValueCommitment region => value_commitment_index region
  | RegionId.Nullifier region => nullifier_index region
  | RegionId.SpendAuthority region => spend_authority_index region
  | RegionId.AddressIntegrity region => address_integrity_index region
  | RegionId.CommitIvk region => commit_ivk_index region
  | RegionId.NoteCommit which region => note_commit_index which region
  | RegionId.NoteCommitOldEquality => 346
  | RegionId.NoteCommitNewWitnessGD => 347
  | RegionId.NoteCommitNewWitnessPkD => 348
  | RegionId.NoteCommitNewWitnessPsi => 349
  | RegionId.OrchardCircuitChecks => 393
  | RegionId.PostNu63CrossAddressChecks => 394
  | RegionId.GadgetLocal region => gadget_local_index region
  end.

Definition region_start_of (region : RegionId.t) : Z :=
  region_start_of_list (region_index_of region) region_starts.
