(** * The Halo2 Vesta SRS ([k = 11], [n = 2048]), assembled literal tables

    The [n + 1] affine Vesta points of [Params::<vesta::Affine>::new(11)]
    ([halo2_proofs/src/poly/commitment.rs]): the generators
    [g_i = hash_to_curve("Halo2-Parameters")([0x00, le32(i)])] and the blind
    generator [w = hash_to_curve("Halo2-Parameters")([0x01])], with the two
    [sqrt_ratio] witnesses (an is-square flag and a root per [hash_to_field]
    output [u_j]) each certificate needs.  Coordinates and roots are reduced
    residues of the Vesta base field [F_{pallas_q}].  The per-shard literal
    tables live in [Orchard/vk_srs_data_{0..15}.v] (entry shape
    [Orchard/vk_srs_entry.v]).

    Untrusted witness input: every entry is verified in-kernel by the shard
    certificates [Garden/Orchard/vk_srs_cert_{0..15}.v] (the witnesses by
    the [SswuVesta.swu_witness_ok] squaring equations, the points by
    recomputing the full [GroupHashVesta] pipeline) and assembled in
    [Garden/Orchard/vk_srs_cert.v].

    Generated by [scripts/generate_vk_srs_witnesses.py]; regenerate with

      python3 scripts/generate_vk_srs_witnesses.py \
        --emit-data Garden/Orchard/vk_srs_data.v --emit-certs Garden/Orchard *)

Require Import Stdlib.ZArith.ZArith.
Require Import Stdlib.Lists.List.
Require Import Garden.Orchard.vk_srs_entry.
Require Import Garden.Orchard.vk_srs_data_0.
Require Import Garden.Orchard.vk_srs_data_1.
Require Import Garden.Orchard.vk_srs_data_2.
Require Import Garden.Orchard.vk_srs_data_3.
Require Import Garden.Orchard.vk_srs_data_4.
Require Import Garden.Orchard.vk_srs_data_5.
Require Import Garden.Orchard.vk_srs_data_6.
Require Import Garden.Orchard.vk_srs_data_7.
Require Import Garden.Orchard.vk_srs_data_8.
Require Import Garden.Orchard.vk_srs_data_9.
Require Import Garden.Orchard.vk_srs_data_10.
Require Import Garden.Orchard.vk_srs_data_11.
Require Import Garden.Orchard.vk_srs_data_12.
Require Import Garden.Orchard.vk_srs_data_13.
Require Import Garden.Orchard.vk_srs_data_14.
Require Import Garden.Orchard.vk_srs_data_15.

Import ListNotations.

Global Open Scope Z_scope.

Module VkSrsData.
  Definition shard_0 : list VkSrsEntry.t := VkSrsData0.shard.
  Definition shard_1 : list VkSrsEntry.t := VkSrsData1.shard.
  Definition shard_2 : list VkSrsEntry.t := VkSrsData2.shard.
  Definition shard_3 : list VkSrsEntry.t := VkSrsData3.shard.
  Definition shard_4 : list VkSrsEntry.t := VkSrsData4.shard.
  Definition shard_5 : list VkSrsEntry.t := VkSrsData5.shard.
  Definition shard_6 : list VkSrsEntry.t := VkSrsData6.shard.
  Definition shard_7 : list VkSrsEntry.t := VkSrsData7.shard.
  Definition shard_8 : list VkSrsEntry.t := VkSrsData8.shard.
  Definition shard_9 : list VkSrsEntry.t := VkSrsData9.shard.
  Definition shard_10 : list VkSrsEntry.t := VkSrsData10.shard.
  Definition shard_11 : list VkSrsEntry.t := VkSrsData11.shard.
  Definition shard_12 : list VkSrsEntry.t := VkSrsData12.shard.
  Definition shard_13 : list VkSrsEntry.t := VkSrsData13.shard.
  Definition shard_14 : list VkSrsEntry.t := VkSrsData14.shard.
  Definition shard_15 : list VkSrsEntry.t := VkSrsData15.shard.

  (** The 2048 SRS entries in index order. *)
  Definition g_entries : list VkSrsEntry.t :=
    shard_0
    ++ shard_1
    ++ shard_2
    ++ shard_3
    ++ shard_4
    ++ shard_5
    ++ shard_6
    ++ shard_7
    ++ shard_8
    ++ shard_9
    ++ shard_10
    ++ shard_11
    ++ shard_12
    ++ shard_13
    ++ shard_14
    ++ shard_15.

  (** The generator points [g_0 .. g_2047], index order. *)
  Definition g_points : list (Z * Z) :=
    List.map VkSrsEntry.point g_entries.

  (** The blind generator [w] and its witnesses
      ([was_square0, root0, was_square1, root1, x, y]). *)
  Definition w_entry : bool * Z * bool * Z * Z * Z :=
    (false,
     19835965361603380029126692985396332089560546869210548035334674302692014722559,
     true,
     11509325903603974387276048908860651638667806997355663785731081592483382181231,
     19782647652113048876238292249473205846269167024536642842614656765564986925173,
     3695361348536575747343819753981312149065541790902967160644660106623299796375).

  Definition w_point : Z * Z :=
    let '(_, _, _, _, x, y) := w_entry in (x, y).
End VkSrsData.
